spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: springServer

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: ${ACCESS_EXPIRATION}
    refreshTokenExpiration: ${REFRESH_EXPIRATION}

  mail:
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 구글에서_발급받은_client_id
            client-secret: 구글에서_발급받은_client_secret
            scope: profile, email
