global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    server: itda-backend
    instance_type: t3.small

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          nodename: ip-172-31-13-141

  - job_name: spring-boot
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: itda-backend
          port: '8080'
