apiVersion: 1

contactPoints:
  - orgId: 1
    name: default-notifier
    receivers:
      - uid: discord-primary
        type: discord
        settings:
          url: ${DISCORD_WEBHOOK_URL}
          title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
          message: >-
            {{ range .Alerts }}**{{ .Annotations.summary }}**
            {{ .Annotations.description }}
            {{ end }}
          use_discord_username: false
        disableResolveMessage: false
